// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/FireShooter.h"
#include "Commands/Move.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    joystick.reset(new Joystick(0));
    
    shootReset.reset(new JoystickButton(joystick.get(), 2));
    shootReset->WhenPressed(new FireShooter(3));
    shootRight.reset(new JoystickButton(joystick.get(), 5));
    shootRight->WhenPressed(new FireShooter(2));
    shootMiddle.reset(new JoystickButton(joystick.get(), 3));
    shootMiddle->WhenPressed(new FireShooter(1));
    shootLeft.reset(new JoystickButton(joystick.get(), 4));
    shootLeft->WhenPressed(new FireShooter(0));

    // SmartDashboard Buttons
    SmartDashboard::PutData("FireShooter: left", new FireShooter(0));
    SmartDashboard::PutData("FireShooter: middle", new FireShooter(1));
    SmartDashboard::PutData("FireShooter: right", new FireShooter(2));
    SmartDashboard::PutData("FireShooter: reset", new FireShooter(3));
    SmartDashboard::PutData("Move", new Move());
    SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<Joystick> OI::getJoystick() {
   return joystick;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
